version: '3.2'

services:
  app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/app  # only dev
    command: ["sh", "-c", "yarn && yarn start"]
    ports:
      - "3000:3000"
